name: Workflow
run-name: ${{ github.actor }} start workflow 🚀
on: [push]
jobs:
  main-workflow:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Install dependencies
        run: npm install
      - name: Audit
        run: npm audit
      - name: Lint
        if: success() || failure()
        run: npm run lint
      - name: Build
        if: success() || failure()
        run: npm run build
      - name: Run tests
        if: success() || failure()
        run: npm run test
      - name: Upload coverage reports to Codecov
        if: success() || failure()
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}