name: Workflow
run-name: ${{ github.actor }} start workflow 🚀
on: [push]
jobs:
  main-workflow:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Install dependencies
        run: npm install
      - name: Audit
        run: npm audit
      - name: Lint
        run: npm run lint
      # - name: Run tests
      #   run: npm run test
      - name: Build
        run: npm run build
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}